### PR TITLE
[magnum]: do not use deprecated Magnum functions

### PR DESCRIPTION
**Pull request by costashatz**
Update for latest upstream Magnum...

### CODE REVIEW

**Comment by jbmouret** [comment]
shouldn't we merge this to `devel' and keep the master to a specific version of Magnum? 

Merging this will break all the installations/containers that did not update Magnum yet, I guess...

**Comment by costashatz** [comment]
We need to first have a `devel` branch.. ;)

I think that I like more the following: `master` is development, other branches or tags for stable things. I can create one for your needs. What do you think?

**Comment by jbmouret** [comment]
Yes, this works for me too, but we need to keep a "release x" branch in that case :)

**Comment by costashatz** [comment]
Good! I'll first make a PR to remove (the dead now) travis and use GitHub actions for CI. Then I'll create separate release branches..

**Comment by costashatz** [comment]
@jbmouret I'll merge this and let me know if things will break for your dockers/setups. Of course the easiest solution is just to use latest Corrade/Magnum etc, but once we make the 1.0.0 release we'll provide installation instructions for specific commits of Corrade/Magnum etc for easy portability and avoid issues.

**Pull request merged**
