### PR TITLE
Create a robot pool

### LINKED ISSUE #99: Include a clone pool
We use this pattern often (to avoid creating a new robot for each evaluation). We could have a polished implementation in robot_dart.

### PR DESCRIPTION
**Pull request by jbmouret**
This is useful when we use robot_dart in many threads and we want to avoid parsing new robots from scratch.

Fix #99

### CODE REVIEW

**Comment by costashatz** [comment]
@jbmouret thanks for this. I pushed a fix for a missing linking flag, but I have one bigger concern. What happens if we want to use to use two robots (and thus there is a need for 2 robot pools with different robots)? The way it is now, this is not possible..

**Comment by jbmouret** [comment]
Good question: 
- we can choose to not cover this case
- we can suppress the singleton access (it is handy but the user can do a global variable instead or link instances)

I would vote for the second case.

**Comment by costashatz** [comment]
> I would vote for the second case.

Agree!

**Comment by costashatz** [comment]
**Merging...**

**Pull request merged**
