### PR TITLE
Small cleaning of Magnum GUI

### PR DESCRIPTION
**Pull request by costashatz**
This PR cleans-up the Magnum GUI.. ~~This is still work in progress I have still to:~~

- [x] Follow the robot_dart style everywhere
- [x] Expose all the functionality of `BaseApplication` to `Graphics` class
- [x] See if I can reduce the duplicate code (e.g., calling functions of `BaseApplication` in `Graphics`)

To speed-up the graphics rate I will open a different PR.

### CODE REVIEW

**Comment by costashatz** [comment]
@jbmouret @Aneoshun This PR is breaking the API of `Magnum::Graphics`: among other things and cleaning, I added a `GraphicsConfiguration` struct as an argument to the constructor instead of the many many arguments (this is the only actual API breakage; the others are internal and should not affect any of your usages). This will enable us to more easily not break the API the next time we would like to add an argument and makes it easier to write/handle default parameters. Can you verify the following?

- That it compiles on your setups and you can run the examples?
- That the behavior of the lights/shadows is as it was before.
- That you are OK to merge (meaning you acknowledge the breaking of the API to adapt your projects)?

Thanks a lot!

**Comment by jbmouret** [comment]
@costashatz Yes, everything works fine for me. 

As we are not using the graphics API right now, I am OK with merging (this is the time for cleaning things).

**Comment by costashatz** [comment]
> @costashatz Yes, everything works fine for me.

Great! I'll wait a few days for @Aneoshun..

Pinging also @ErickKramer as he was using the library.

**Comment by Aneoshun** [comment]
Hi @costashatz, 

I am pinging my student @Lookatator as he is using this API every day. He will be better suited than me to comment on this PR.

**Comment by ErickKramer** [comment]
Hi @costashatz 
Thank you for pinging me. I have no issue with the cleaning. I finished the work I was doing with the library. Thank you for all the help provided.

**Comment by Lookatator** [comment]
Hi @costashatz 

It works perfectly for me as well. I am totally OK with merging 😃

**Comment by costashatz** [comment]
**Merging..**

**Pull request merged**
