### PR TITLE
Use Egl instead of Glx

### PR DESCRIPTION
**Pull request by costashatz**
This PR replaces `WindowlessGlxAppilcation` with the more powerful `WindowlessEglApplication` for Linux. Unfortunately, we are stuck with `WindowlessCglApplication` for Mac.

~~We also fix a small issue with OpenGL/GLFW3 detection..~~

### CODE REVIEW

**Comment by costashatz** [comment]
@jbmouret have a try on this one in your dockers! In essence, I replaced all glx with egl (see the `ci/install_magnum.sh`). If this works for you, I'll merge..

Now we can have windowless apps without dummy (or real) xservers! And in theory, GLFW should be better with egl!

**Comment by jbmouret** [comment]
I've run `ci/install_magnum.sh` then `waf configure`

The library compiles but not the examples.

```
[ 44/119] Linking build/pendulum
./libRobotDARTMagnum.a(cube_map_color.cpp.4.o): In function `CubeMapColor':
/home/pal/robot_dart/build/../src/robot_dart/gui/magnum/gs/cube_map_color.cpp:37: undefined reference to `Magnum::GL::AbstractShaderProgram::attachShaders(std::initializer_list<Corrade::Containers::Reference<Magnum::GL::Shader> >)'
./libRobotDARTMagnum.a(cube_map.cpp.4.o): In function `CubeMap':
/home/pal/robot_dart/build/../src/robot_dart/gui/magnum/gs/cube_map.cpp:36: undefined reference to `Magnum::GL::AbstractShaderProgram::attachShaders(std::initializer_list<Corrade::Containers::Reference<Magnum::GL::Shader> >)'
./libRobotDARTMagnum.a(shadow_map.cpp.4.o): In function `ShadowMap':
/home/pal/robot_dart/build/../src/robot_dart/gui/magnum/gs/shadow_map.cpp:32: undefined reference to `Magnum::GL::AbstractShaderProgram::attachShaders(std::initializer_list<Corrade::Containers::Reference<Magnum::GL::Shader> >)'
./libRobotDARTMagnum.a(shadow_map_color.cpp.4.o): In function `ShadowMapColor':
/home/pal/robot_dart/build/../src/robot_dart/gui/magnum/gs/shadow_map_color.cpp:32: undefined reference to `Magnum::GL::AbstractShaderProgram::attachShaders(std::initializer_list<Corrade::Containers::Reference<Magnum::GL::Shader> >)'
./libRobotDARTMagnum.a(phong_multi_light.cpp.4.o): In function `PhongMultiLight':
/home/pal/robot_dart/build/../src/robot_dart/gui/magnum/gs/phong_multi_light.cpp:39: undefined reference to `Magnum::GL::AbstractShaderProgram::attachShaders(std::initializer_list<Corrade::Containers::Reference<Magnum::GL::Shader> >)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by costashatz** [comment]
> but not the examples.

This smells like a bad installation procedure... Maybe two magnums installed? Or some error that was ignored?

**Comment by jbmouret** [comment]
Yes, I will try again by removing all the current magnum...

**Comment by jbmouret** [comment]
So, it did compile in our docker. Should I try on mac too?

**Pull request merged**
