### PR TITLE
Adding ghost robots and other visualizations

### LINKED ISSUE #40: Add API for easily adding markers/ghost robots and other visualizations
We should add helper functions to RobotDARTSimu for easily adding visualization things. Here's a list:

- Ghost robots (clone of robots with different colors/shading that do not interact with the environment and are there just for visualization purposes) --- maybe this should go to Robot class
- Add visualization spheres
- Add visualization cubes/rectangles
- ...

@jbmouret @dalinel @PedroDesRobots let me know if you have something to add..

### PR DESCRIPTION
**Pull request by costashatz**
This PR fixes #40.. ~~Still **WIP**..~~ This will break the GUI API slightly again..

### CODE REVIEW

**Comment by costashatz** [comment]
At the moment we can clone robots in `ghost` mode: the user can choose the color of the ghost robot and ghost robots have no shadows. Here's an example:
image

I am also thinking to make it possible to select whether a camera should render ghost robots and other visualizations. For example, we might want the main camera to display the ghost robots/visualizations for inspection, but the sensor cameras to not display them.

My thoughts are as follows:

*Do we really need this? I mean we would usually use the main camera only when debugging. When running the learning algorithms or other simulation, it will be rare that we would want a gui visualization as this will slow things down. So one can create 2 executables with defines: one for inspection and another for running without the GUI. On the other hand, being able to choose which objects get displayed and which not might be useful in other cases as well.*

@jbmouret @dalinel @PedroDesRobots let me know what you think.. I will add the rest of the visualizations as well (spheres, cubes, etc.)..

**Comment by jbmouret** [comment]
On our side, we are not using cameras as sensors, so this does not make any difference for now. But the idea of 'ghosts' is that they do not appear on sensors, so we might want to keep this in mind anyway.

**Comment by costashatz** [comment]
> But the idea of 'ghosts' is that they do not appear on sensors

It was much easier to do than I thought! I pushed the fix. No we can choose whether we want to draw ghosts objects, both in the main camera and every other sensor..

**Comment by costashatz** [comment]
@jbmouret @dalinel @PedroDesRobots this should finished. I will not include the ConvexHull in this iteration... Let me know if I can merge..

**Comment by dalinel** [comment]
It is ok for me !

**Comment by costashatz** [comment]
@Aneoshun @Lookatator pinging you in case this is breaking your code (we are breaking slightly the GUI API)..

**Comment by Aneoshun** [comment]
Hey, that's a fantastic feature! Thanks. 
If it works for you, you can merge. We have pined the commit SHA of all the modules used and we will remain a bit behind master, while our current problems with dart are not solved.

**Comment by costashatz** [comment]
> Hey, that's a fantastic feature! Thanks.
> If it works for you, you can merge. We have pined the commit SHA of all the modules used and we will remain a bit behind master

Great! Thanks for the information!

> while our current problems with dart are not solved

What problems are you facing with DART? Or you meant tasks?

**Comment by Aneoshun** [comment]
The "memory leak" fix introduced last week causes some issues in thread safety with random segfaults during sferes experiments.
https://github.com/dartsim/dart/issues/1468

**Comment by costashatz** [comment]
> The "memory leak" fix introduced last week causes some issues in thread safety with random segfaults during sferes experiments.
> [dartsim/dart#1468](https://github.com/dartsim/dart/issues/1468)

@Aneoshun thank you for letting us know. Thankfully we do not really depend on the latest master for robot_dart, but it's good to know. Can you make a separate issue for this? Thanks again!

**Comment by Aneoshun** [comment]
A separate issue, where? On Robot_dart, just to keep track of the issue in dart?

**Comment by costashatz** [comment]
> On Robot_dart, just to keep track of the issue in dart?

yes thank you!

**Comment by Aneoshun** [comment]
done

**Pull request merged**
