### PR TITLE
minor improvements to wscript (-fPIC) and dart.py + add line number in assert

### PR DESCRIPTION
**Pull request by jbmouret**
A few minor improvements:
- add `-fPIC`
- add a directory in dart.py to find dart
- add line number in ROBOT_DART_ASSERT

### CODE REVIEW

**Review by costashatz — APPROVED** [review]
Two very minor comments. Other than this. Thanks! It's looking good!

**Comment by costashatz** [comment]
@jbmouret this should finalized now. I did some minor modifications (e.g. when building shared, we do not need `-fPIC`; the code generated is position independent by definition) and I updated all searches for all libs (I added also search for the new M1 chips that some students of mine had problems with).. Let me know if this is working for you..

**Comment by costashatz** [comment]
@jbmouret is this OK to merge?

**Comment by jbmouret** [comment]
yes (in which case do we want to remove -fPIC?)

**Comment by costashatz** [comment]
> (in which case do we want to remove -fPIC?)

If we are building shared libs, PIC is already there by definition so the flag is useless. Also, I cannot see an application at the moment, but maybe someone finds some weird application for removing -fPIC (e.g. an architecture/CPU not allowing PIC).

**Pull request merged**
