### PR TITLE
working on #58 (separate build for examples)

### PR DESCRIPTION
**Pull request by jbmouret**
It does not work yet (RobotDARTSimu is not linked)

### CODE REVIEW

**Comment by jbmouret** [comment]
It seems to me that the build context does not include RobotDARTSimu (since this is a different build object) and therefore we cannot use the libraries... we could simply do `./waf --examples` but I am not sure we can do `./waf examples'

In Limbo, it worked but we had no link, I think. But maybe there is another issue...

**Comment by costashatz** [comment]
We need dependencies: see [here](https://waf.io/book/#_dependencies).

**Comment by jbmouret** [comment]
What I did (last commit) adds the dependency, right?

**Comment by costashatz** [comment]
> What I did (last commit) adds the dependency, right?

I guess so. It compiles on my arch-linux system. I will try also the Ubuntu..

**Comment by costashatz** [comment]
@jbmouret this is working on all my machines. Should we **merge**?

**Comment by jbmouret** [comment]
I wanted to first remove the redundancy between the graphics & non-graphics version (make a loop instead).

**Comment by jbmouret** [comment]
Should we keep the hexapod example? I like hexapods but depending on the external controller makes things complex for nothing.

We could also keep it and adds the file for its controller (not depending on the resibots controller). It should be a single file that could be in the example.

**Comment by costashatz** [comment]
> Should we keep the hexapod example? I like hexapods but depending on the external controller makes things complex for nothing.

Let's remove it.. It doesn't really add anything to `robot_dart`. We can keep a hexapod example where it does not move and just stays in place with `SERVO` actuators. What do you think?

**Comment by jbmouret** [comment]
I am all for removing things!

**Comment by jbmouret** [comment]
(can you check the last push? we can merge after this)

**Comment by costashatz** [comment]
> (can you check the last push? we can merge after this)

Did you remove the hexapod example?

**Comment by jbmouret** [comment]
Not yet. We could do a second PR.

**Comment by costashatz** [comment]
> (can you check the last push? we can merge after this)

It's working.. We can **merge**..

**Pull request merged**
