### PR TITLE
Transparent objects and colored shadows

### PR DESCRIPTION
**Pull request by costashatz**
My original code was not visualizing transparent objects properly. This PR fixes this and adds one additional feature of having colored shadows for transparent objects (at the moment shadows do not pass through the transparent objects, which would be cool but not important for robot_dart). Here's an example:

image

I will merge once I test a few things...

### CODE REVIEW

**Comment by costashatz** [comment]
@Aneoshun @jbmouret can you test if everything is working properly and if the visualization speed is normal for running the examples?

**Comment by Aneoshun** [comment]
Hi @costashatz 

I test on macos, starting from a working master branch. After git pull, git checkout..., ./waf clean, ./waf:
It compiles, but shows this for the meshes and hexapod examples:
```
~/git/robot_dart$ ./build/hexapod
[robot_dart WARNING]: "Shadows are not working properly on Mac! Disable them if you experience unexpected behavior.."
Platform::GlfwApplication: warning: the executable is not a HiDPI-enabled app bundle
GL::AbstractShaderProgram: location of uniform 'drawTransparentShadowsUniform' cannot be retrieved
GL::AbstractShaderProgram: location of uniform 'drawTransparentShadowsUniform' cannot be retrieved
GL::Shader::compile(): compilation of geometry shader 2 failed with the following message:
ERROR: 2:16: interpolation qualifier 'flat' must precede storage qualifiers
ERROR: 2:36: Use of undeclared identifier 'lightNumber'
Assertion Magnum::GL::Shader::compile({vert, geom, frag}) failed in ../src/robot_dart/gui/magnum/gs/cube_map.cpp on line 31
Abort trap: 6

```

**Comment by jbmouret** [comment]
Same here, I guess: it works as before (shadows are OK) but (1) where should I test the transparent objects? (2) I get warnings:
```
[robot_dart WARNING]: "Shadows are not working properly on Mac! Disable them if you experience unexpected behavior.."
Platform::GlfwApplication: warning: the executable is not a HiDPI-enabled app bundle
GL::AbstractShaderProgram: location of uniform 'drawTransparentShadowsUniform' cannot be retrieved
GL::AbstractShaderProgram: location of uniform 'drawTransparentShadowsUniform' cannot be retrieved
GL::AbstractShaderProgram::link(): linking succeeded with the following message:
WARNING: Output of geometry shader 'lightNumber' not read by fragment shader
GL::AbstractShaderProgram::link(): linking succeeded with the following message:
WARNING: Output of geometry shader 'lightNumber' not read by fragment shader
```

**Comment by costashatz** [comment]
> Same here, I guess: it works as before (shadows are OK) but (1) where should I test the transparent objects? (2) I get warnings:

Did you use the latest commit (I just committed a few minutes ago)?

**Comment by costashatz** [comment]
> WARNING: Output of geometry shader 'lightNumber' not read by fragment shader

This warning is okay. I will try to suppress it but it is not important.

I just pushed a last fix.. This should make it work. I do not have a transparent object example yet. I will do one now..

**Comment by costashatz** [comment]
@Aneoshun @jbmouret now there is a transparent example and the errors should have been corrected. Let me know if it is okay:

- Compiling/running okay
- Visualization speed

Thanks!

**Comment by jbmouret** [comment]
OK for me on mac.

**Comment by Aneoshun** [comment]
Hum.. I get a segfault on my side. 
Hexapod and Meshes works well, but Transparent and Tutorial lead to:
```
./build/transparent
[robot_dart WARNING]: "Shadows are not working properly on Mac! Disable them if you experience unexpected behavior.."
Platform::GlfwApplication: warning: the executable is not a HiDPI-enabled app bundle
GL::AbstractShaderProgram::link(): linking succeeded with the following message:
WARNING: Output of geometry shader 'lightNumber' not read by fragment shader
GL::AbstractShaderProgram::link(): linking succeeded with the following message:
WARNING: Output of geometry shader 'lightNumber' not read by fragment shader
Segmentation fault: 11
```

lldb without optimisation and with -ggdb3 leads to the following trace: 
```
~/git/robot_dart$ lldb ./build/transparent
(lldb) target create "./build/transparent"
Current executable set to './build/transparent' (x86_64).
(lldb) run
Process 43581 launched: '/Users/antoinecully/git/robot_dart/build/transparent' (x86_64)
dyld: Library not loaded: @rpath/libMagnumMeshTools.2.dylib
  Referenced from: /Users/antoinecully/git/robot_dart/build/transparent
  Reason: image not found
Process 43581 stopped
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001000cf4fe dyld`__abort_with_payload + 10
dyld`__abort_with_payload:
->  0x1000cf4fe <+10>: jae    0x1000cf508               ; <+20>
    0x1000cf500 <+12>: movq   %rax, %rdi
    0x1000cf503 <+15>: jmp    0x1000cda21               ; cerror_nocancel
    0x1000cf508 <+20>: retq   
Target 0: (transparent) stopped.
(lldb) bt
* thread #1, stop reason = signal SIGABRT
  * frame #0: 0x00000001000cf4fe dyld`__abort_with_payload + 10
    frame #1: 0x00000001000f8a4e dyld`abort_with_payload_wrapper_internal + 80
    frame #2: 0x00000001000f8a80 dyld`abort_with_payload + 9
    frame #3: 0x00000001000f6263 dyld`dyld::halt(char const*) + 463
    frame #4: 0x0000000100083d41 dyld`dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 7422
    frame #5: 0x000000010007d227 dyld`dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 453
    frame #6: 0x000000010007d025 dyld`_dyld_start + 37
```

**Comment by costashatz** [comment]
> Transparent and Tutorial lead to:

Can you try the version of them without graphics?

**Comment by Aneoshun** [comment]
both work fine without graphics

**Comment by costashatz** [comment]
> both work fine without graphics

Try the tutorial in the master branch.. The issue does not seem related to the new changes..

**Comment by Aneoshun** [comment]
Tutorial with and without graphics work fine on Master.

**Comment by costashatz** [comment]
> Tutorial with and without graphics work fine on Master.

are you sure you link correctly to Magnum? It says it cannot load the `MeshTools` library. I didn't touch this part at all (it's in DART integration, not in robot_dart). Can you clean everything and re-try?

**Comment by Aneoshun** [comment]
Indeed, you are correct. I just noticed that robot_dart does not install the library properly, and that migh cause an issue when linking: 
```
./waf install
Waf: Entering directory `/Users/antoinecully/git/robot_dart/build'
Waf: Leaving directory `/Users/antoinecully/git/robot_dart/build'
source not found: 'build/libRobotDARTSimu.so' in bld(target='', idx=46, install_task=
	{task 4422651608: inst  -> }, dest='${PREFIX}/lib', tg_idx_count=46, meths=['process_install_task', 'process_rule', 'process_source'], _name='', source=[], install_to='${PREFIX}/lib', path=/Users/antoinecully/git/robot_dart, install_from='build/libRobotDARTSimu.so', posted=True, type='install_files', features=['install_task']) in /Users/antoinecully/git/robot_dart
```

I copied the `*.dylib` files manually and it works.

Here is what I have with Transparent. I get several blue dots on the ground that do not make sense to me (but I have transparent spheres). 
Screenshot 2019-11-23 at 10 44 04

**Comment by costashatz** [comment]
> I just noticed that robot_dart does not install the library properly

Hmmm! We should fix this...!

> I get several blue dots on the ground that do not make sense to me (but I have transparent spheres).

This is weird, but I am not sure where this comes from. We had some issues with textures in Mac before right? There is definitely an issue with textures as there should be two lights, and thus 2 shadows but I only see one...

Do the other examples have 2 shadows?

**Comment by Aneoshun** [comment]
Hexapod has only on shadow on mac.

**Comment by costashatz** [comment]
> Hexapod has only on shadow on mac.

Yes. This is thus un-related to this PR.

@jbmouret are you getting the same behavior? Or you see 2 shadows and the colored shadows okay?

**Comment by jbmouret** [comment]
I also get the blue dots.
Screenshot 2019-11-23 at 13 37 18

**Comment by costashatz** [comment]
OK thanks a lot to both of you @Aneoshun and @jbmouret! Since this is not related to the new changes, I will merge this PR and my next PR is unit tests.. After this hopefully I will find some time to see why this is not working in Mac.

**Pull request merged**
