### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by costashatz**
A bit of cleaning up in the examples and utils..

### CODE REVIEW

**Comment by costashatz** [comment]
@ErickKramer this PR changes a bit the `set_base_pose` that you introduced in #26.. Let me know if this breaks anything for you..

**Comment by ErickKramer** [comment]
> @ErickKramer this PR changes a bit the `set_base_pose` that you introduced in #26.. Let me know if this breaks anything for you..

It's alright for me. I finished the work I was doing with robot_dart ;). 

Thank you for letting me know though

**Comment by costashatz** [comment]
> It's alright for me. I finished the work I was doing with robot_dart ;).

@ErickKramer too bad you stopped working with robot_dart..

**Comment by costashatz** [comment]
**Merging...**

**Pull request merged**
