### PR TITLE
Python binding through pybind11

### PR DESCRIPTION
**Pull request by costashatz**
This provides python bindings to robot_dart. This is still work in progress, but I would like to get your opinion @Aneoshun and @jbmouret.. In order to test it, you need to have compiled DART with python support and have installed it.

Features already transferred to python:
- Robot class and dart skeleton through the official `dartpy`
- RobotDARTSimu class (except descriptors)
- RobotControl class basic functionality; even inheriting the base class and creating your custom controllers in python
- Graphics on single-thread (including lights, material etc through the official magnum python bindings)
- Cameras and image retrieval
- An example usage
- **Access to robot skeleton in RobotControl class**
- **Multi-thread graphics support; added an example**
- **Basic installation instructions and examples**

Remaining features/things:
- ~~Access to robot skeleton in RobotControl class~~
- ~~Clean up the code~~
- ~~Multi-thread graphics support~~
- Support for adding/creating descriptors
- **Correct cloning of controllers written in python**
- ~~Documentation~~

### CODE REVIEW

**Comment by costashatz** [comment]
Did you have time to have a look at it @jbmouret and @Aneoshun ?

**Comment by Aneoshun** [comment]
No sorry. I am not using python for experiments at the moment, so it is not obvious for me to test it quickly. Is there something that you want me to have a look specifically? Like running the python examples?

**Comment by costashatz** [comment]
> No sorry.

No worries.

> Like running the python examples?

Yeah I just need to verify that it works in several computers, not just mine. Can you just compile and run the python example? You need to do the following (we need python3):

- Build DART with python enabled (`-DDART_BUILD_DARTPY=ON` parameter on cmake)
- `python3 ./waf configure --python`
- `python3 ./waf`
- `python3 src/python/example.py` # single core example
- `python3 src/python/example_parallel.py` # mutli-core example

The single core example should create a window and display an arm. The multi-core example should produce 15 pictures (with different names and view angles).

Thanks a lot!

**Comment by jbmouret** [comment]
Everything compiled on my side but dartpy is not working (maybe because I already have dart installed somewhere).

```python3
➜  ~ python3
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dartpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dartpy.so, 2): Symbol not found: __ZN5boost6system16generic_categoryEv
  Referenced from: /usr/local/opt/fcl04/lib/libfcl.6.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_system-mt.dylib
 in /usr/local/opt/fcl04/lib/libfcl.6.dylib
```

**Comment by costashatz** [comment]
> Everything compiled on my side but dartpy is not working (maybe because I already have dart installed somewhere).

Can you try uninstalling everything related to DART and reinstalling it with the python bindings (make sure to select python3 in the compilation of DART)?

I have 2-3 computers with fresh installations of different OSes (arch linux and ubuntu) and I will try also to see.

**Comment by jbmouret** [comment]
I recompiled DART with `cmake -DDART_BUILD_DARTPY=ON  -DDART_ENABLE_SIMD=ON ..` but I have the same issue with FCL.

I think this is a problem from my computer, but this prevents me from testing.

**Comment by costashatz** [comment]
@Aneoshun @jbmouret I think this PR is ready to be merged now. I tested and it is working under ArchLinux, Ubuntu 18.04 and Ubuntu 19.04. I still didn't solve the issue of cloning the controllers made in python and I haven't implemented the porting of descriptors. Nevertheless, these two features are not very important. I will open an issue to not forget them.

Let me know if you are OK to merge or if you managed to test the python bindings (I added some installation instructions).

**Comment by costashatz** [comment]
> Let me know if you are OK to merge or if you managed to test the python bindings (I added some installation instructions).

@jbmouret @Aneoshun  I'll merge by tonight if you do not have any objection..

**Comment by jbmouret** [comment]
I think you can merge: it compiles on my computer. It fails at the execution, but I think this is not your fault.

**Comment by jbmouret** [comment]
interestingly, I can now import dartpy... but not robotDART, with the exact same issue (FCL + boost). I guess my FCL is linked to a different boost library and it causes problems.

**Comment by costashatz** [comment]
> interestingly, I can now import dartpy... but not robotDART, with the exact same issue (FCL + boost). I guess my FCL is linked to a different boost library and it causes problems.

This is weird! Can you cleanly install all components? DART, FCL, etc.?

**Comment by jbmouret** [comment]
This might be related to c++14 flags. I will investigate more.

**Comment by jbmouret** [comment]
I fixed my FCL problem! (there was an old fcl 0.4 installed by an old version of dart by brew).

... but now I get a seg fault when I instantiate the robot (robot_dart works well and the import works).

```
 thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x48)
    frame #0: 0x000000010d11d1a8 libdart.6.10.0.dylib`dart::dynamics::Joint::setName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) + 24
libdart.6.10.0.dylib`dart::dynamics::Joint::setName:
->  0x10d11d1a8 <+24>: movzbl 0x48(%rdi), %ecx
    0x10d11d1ac <+28>: movq   %rcx, %rax
    0x10d11d1af <+31>: shrq   %rax
    0x10d11d1b2 <+34>: movq   %rax, %rdx
Target 0: (Python) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x48)
  * frame #0: 0x000000010d11d1a8 libdart.6.10.0.dylib`dart::dynamics::Joint::setName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) + 24
    frame #1: 0x000000010d11d12b libdart.6.10.0.dylib`dart::dynamics::Joint::setAspectProperties(dart::common::MakeCloneable<dart::common::Aspect::Properties, dart::dynamics::detail::JointProperties> const&) + 27
    frame #2: 0x000000010d043873 libdart.6.10.0.dylib`dart::common::detail::EmbeddedPropertiesAspect<dart::common::CompositeTrackingAspect<dart::dynamics::Joint>, dart::common::EmbeddedPropertiesAspect<dart::dynamics::Joint, dart::dynamics::detail::JointProperties>, dart::dynamics::detail::JointProperties, dart::common::MakeCloneable<dart::common::Aspect::Properties, dart::dynamics::detail::JointProperties>, &(void dart::common::detail::DefaultSetEmbeddedProperties<dart::common::EmbeddedPropertiesAspect<dart::dynamics::Joint, dart::dynamics::detail::JointProperties>, dart::common::MakeCloneable<dart::common::Aspect::Properties, dart::dynamics::detail::JointProperties> >(dart::common::EmbeddedPropertiesAspect<dart::dynamics::Joint, dart::dynamics::detail::JointProperties>*, dart::common::MakeCloneable<dart::common::Aspect::Properties, dart::dynamics::detail::JointProperties> const&)), &(dart::common::MakeCloneable<dart::common::Aspect::Properties, dart::dynamics::detail::JointProperties> const& dart::common::detail::DefaultGetEmbeddedProperties<dart::common::EmbeddedPropertiesAspect<dart::dynamics::Joint, dart::dynamics::detail::JointProperties>, dart::common::MakeCloneable<dart::common::Aspect::Properties, dart::dynamics::detail::JointProperties> >(dart::common::EmbeddedPropertiesAspect<dart::dynamics::Joint, dart::dynamics::detail::JointProperties> const*))>::setComposite(dart::common::Composite*) + 67
    frame #3: 0x000000010d0a1d30 libdart.6.10.0.dylib`dart::dynamics::FreeJoint::FreeJoint(dart::dynamics::FreeJoint::Properties const&) + 1024
    frame #4: 0x000000010d752285 libdart-utils-urdf.6.10.0.dylib`std::__1::pair<dart::dynamics::FreeJoint*, dart::dynamics::BodyNode*> dart::dynamics::Skeleton::createJointAndBodyNodePair<dart::dynamics::FreeJoint, dart::dynamics::BodyNode>(dart::dynamics::BodyNode*, dart::dynamics::FreeJoint::Properties const&, dart::dynamics::BodyNode::Properties const&) + 69
    frame #5: 0x000000010d751ab7 libdart-utils-urdf.6.10.0.dylib`dart::utils::createDartJointAndNodeForRoot(dart::common::detail::ComposeData<dart::common::detail::CompositeData<std::__1::map<std::__1::type_index, std::__1::unique_ptr<dart::common::Aspect::Properties, std::__1::default_delete<dart::common::Aspect::Properties> >, std::__1::less<std::__1::type_index>, std::__1::allocator<std::__1::pair<std::__1::type_index const, std::__1::unique_ptr<dart::common::Aspect::Properties, std::__1::default_delete<dart::common::Aspect::Properties> > > > >, dart::common::detail::GetProperties>, dart::common::detail::GetProperties, dart::dynamics::BodyNode> const&, dart::dynamics::BodyNode*, std::__1::shared_ptr<dart::dynamics::Skeleton>, unsigned int) + 1383
    frame #6: 0x000000010d74f2d2 libdart-utils-urdf.6.10.0.dylib`dart::utils::DartLoader::createDartJointAndNode(urdf::Joint const*, dart::common::detail::ComposeData<dart::common::detail::CompositeData<std::__1::map<std::__1::type_index, std::__1::unique_ptr<dart::common::Aspect::Properties, std::__1::default_delete<dart::common::Aspect::Properties> >, std::__1::less<std::__1::type_index>, std::__1::allocator<std::__1::pair<std::__1::type_index const, std::__1::unique_ptr<dart::common::Aspect::Properties, std::__1::default_delete<dart::common::Aspect::Properties> > > > >, dart::common::detail::GetProperties>, dart::common::detail::GetProperties, dart::dynamics::BodyNode> const&, dart::dynamics::BodyNode*, std::__1::shared_ptr<dart::dynamics::Skeleton>, unsigned int) + 1074
    frame #7: 0x000000010d74e306 libdart-utils-urdf.6.10.0.dylib`dart::utils::DartLoader::createSkeletonRecursive(urdf::ModelInterface const*, std::__1::shared_ptr<dart::dynamics::Skeleton>, urdf::Link const*, dart::dynamics::BodyNode*, dart::common::Uri const&, std::__1::shared_ptr<dart::common::ResourceRetriever> const&, unsigned int) + 534
    frame #8: 0x000000010d74cbb1 libdart-utils-urdf.6.10.0.dylib`dart::utils::DartLoader::modelInterfaceToSkeleton(urdf::ModelInterface const*, dart::common::Uri const&, std::__1::shared_ptr<dart::common::ResourceRetriever> const&, unsigned int) + 257
    frame #9: 0x000000010d74c63f libdart-utils-urdf.6.10.0.dylib`dart::utils::DartLoader::parseSkeleton(dart::common::Uri const&, std::__1::shared_ptr<dart::common::ResourceRetriever> const&, unsigned int) + 159
    frame #10: 0x000000010c5b66ec RobotDART.cpython-36m-darwin.so`robot_dart::Robot::_load_model(this=0x000000010f814bb0, filename=<unavailable>, packages=size=0, is_urdf_string=<unavailable>) at robot.cpp:778:35 [opt]
    frame #11: 0x000000010c5b5bbe RobotDART.cpython-36m-darwin.so`robot_dart::Robot::Robot(this=0x000000010f814bb0, model_file="res/models/arm.urdf", packages=size=0, robot_name=<unavailable>, is_urdf_string=<unavailable>, cast_shadows=true, damages=size=0) at robot.cpp:32:257 [opt]
    frame #12: 0x000000010c5b783f RobotDART.cpython-36m-darwin.so`robot_dart::Robot::Robot(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::vector<robot_dart::RobotDamage, std::__1::allocator<robot_dart::RobotDamage> >) [inlined] robot_dart::Robot::Robot(this=<unavailable>, model_file=<unavailable>, packages=size=0, robot_name="arm") at robot.cpp:33:5 [opt]
    frame #13: 0x000000010c5b7820 RobotDART.cpython-36m-darwin.so`robot_dart::Robot::Robot(this=0x000000010f814bb0, model_file="res/models/arm.urdf", robot_name="arm", is_urdf_string=<unavailable>, cast_shadows=<unavailable>, damages=<unavailable>) at robot.cpp:39 [opt]
    frame #14: 0x000000010c567ed1 RobotDART.cpython-36m-darwin.so`robot_dart::Robot* pybind11::detail::initimpl::construct_or_initialize<robot_dart::Robot, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, 0>(args=<unavailable>, args=<unavailable>, args=0x00007ffeefbfeb9f) at init.h:61:68 [opt]
```

**Comment by costashatz** [comment]
> I guess this could come from some issue with -march native again.

Yes this is the classic issue. Try installing everything without the native flags.. The performance gain is not huge..

**Comment by jbmouret** [comment]
That's a lot of work to recompile everything again. I am afraid I will break the C++ part. I will see later (it seems that the python part IS compiled with AVX, so it *should* work)

**Comment by jbmouret** [comment]
So, I got it to work, but I have to import dartpy AFTER RobotDART.

```python
import RobotDART as rd
import dartpy
```

One possible lead is that dartpy is linking statically with Dart but we don't. This might create some conflict between the two libs. Or we do a few things in a particular way when we load robot_dart but dartpy does differently...

... but really, I do not know what is wrong :)

This might come from my installation (I did not try in any 'clean' environment and I have installed different versions of Dart for several years).

But the fix is simple and should work on Linux. Should I push it and call it a day? next step will be to test in conda/mac (apparently I found there is a special flag to add, for a s

**Comment by costashatz** [comment]
> One possible lead is that dartpy is linking statically with Dart but we don't. This might create some conflict between the two libs.

I don't think so.

> but really, I do not know what is wrong :)

Me neither.

> This might come from my installation (I did not try in any 'clean' environment and I have installed different versions of Dart for several years).

Might be the case. I guess you have some file/library forgotten somewhere.

> But the fix is simple and should work on Linux.

Can you try in the [py_fix](https://github.com/resibots/robot_dart/tree/py_fix) branch? I was including dartpy in code (which is not needed), and I guess this could have some issues.

**Comment by jbmouret** [comment]
py_fix works, except this at the end:

```
[ 0.          1.57094097 -0.49035861  0.7002893 ]
Traceback (most recent call last):
  File "src/python/example.py", line 76, in <module>
    print(desc._states[-1])
NameError: name 'desc' is not defined
```

**Comment by costashatz** [comment]
> Traceback (most recent call last):
>   File "src/python/example.py", line 76, in <module>
>     print(desc._states[-1])
> NameError: name 'desc' is not defined

Hmm.. This is weird.

Can you add a print inside this [function](https://github.com/resibots/robot_dart/blob/py_fix/src/python/example.py#L28) to see if the descriptor is being called correctly?

**Comment by jbmouret** [comment]
Sorry, I had some unstaged change that was polluting the test. It works if I import dartpy after RobotDART.

**Comment by costashatz** [comment]
> Sorry, I had some unstaged change that was polluting the test. It works if I import dartpy after RobotDART.

If you import dartpy before RobotDART, it doesn't?

**Comment by jbmouret** [comment]
yes, same segv.

**Comment by costashatz** [comment]
> yes, same segv.

This is interesting.. Let me put one python testing on Travis for Mac. Maybe we will find something there..

**Pull request merged**
